import React, { useState, useEffect, useRef } from 'react';
import {
  Menu,
  Search,
  Bell,
  Sparkles,
  Command,
  RefreshCw,
  CheckCircle2,
} from 'lucide-react';
import type { ViewType, ActivityItem } from '../../types';

interface NavbarProps {
  currentView: ViewType;
  onOpenMobileMenu: () => void;
  searchQuery?: string;
  onSearchChange?: (query: string) => void;
  onTriggerScan?: () => void;
  activities?: ActivityItem[];
  isBackendConnected?: boolean;
  onRetryConnection?: () => void;
}

const VIEW_TITLES: Record<ViewType, { title: string; subtitle: string }> = {
  dashboard: {
    title: 'Command Dashboard',
    subtitle: 'Real-time overview of AI lead discovery, conversion velocity, and ICP scoring',
  },
  icp: {
    title: 'ICP Configuration',
    subtitle: 'Define target buyer personas, firmographics, tech stack signals, and scoring weights',
  },
  discovery: {
    title: 'Autonomous Discovery Engine',
    subtitle: 'Search corporate domains, review staged candidates with provenance, and bulk-ingest into CRM',
  },
  leads: {
    title: 'Discovered Leads Repository',
    subtitle: 'Review, filter, and qualify prospects generated by LeadForge autonomous agents',
  },
  pipeline: {
    title: 'Deal Pipeline Kanban',
    subtitle: 'Track outreach status, active buyer conversations, and closed won pipeline',
  },
  knowledge: {
    title: 'Knowledge Base & Context Hub',
    subtitle: 'Sales collateral, pricing sheets, and battlecards powering autonomous personalization',
  },
  outreach: {
    title: 'Outreach & CRM Engagement',
    subtitle: 'Automated 3-step personalized sequences, execution safety controls, and CRM synchronization',
  },
  settings: {
    title: 'Platform Settings & Connectors',
    subtitle: 'Manage Crawlee source profiles, external API connectors, rate limits, and platform safety controls',
  },
};

export const Navbar: React.FC<NavbarProps> = ({
  currentView,
  onOpenMobileMenu,
  searchQuery = '',
  onSearchChange,
  onTriggerScan,
  activities = [],
  isBackendConnected = true,
  onRetryConnection,
}) => {
  const [showNotifications, setShowNotifications] = useState(false);
  const [isScanning, setIsScanning] = useState(false);
  const [scanMessage, setScanMessage] = useState<string | null>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);

  const viewInfo = VIEW_TITLES[currentView];

  // Hotkey listener: Ctrl + K or Cmd + K focuses search bar
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        searchInputRef.current?.focus();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const handleSimulateScan = () => {
    setIsScanning(true);
    setScanMessage('Agent scanning public registers and tech graphs...');
    setTimeout(() => {
      setIsScanning(false);
      if (onTriggerScan) {
        onTriggerScan();
      }
      setScanMessage('Completed: New high-match leads discovered and synced to SQLite!');
      setTimeout(() => setScanMessage(null), 3500);
    }, 1200);
  };

  return (
    <header className="sticky top-0 z-30 flex h-18 w-full items-center justify-between border-b border-slate-200/90 bg-white/95 px-4 sm:px-6 backdrop-blur-md shadow-2xs">
      {/* Left Title / Hamburger */}
      <div className="flex items-center gap-3">
        <button
          onClick={onOpenMobileMenu}
          className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-slate-900 lg:hidden cursor-pointer"
          aria-label="Open mobile menu"
        >
          <Menu className="h-5 w-5" />
        </button>

        <div>
          <h1 className="text-base sm:text-lg font-bold tracking-tight text-slate-900 flex items-center gap-2">
            {viewInfo.title}
          </h1>
          <p className="hidden text-xs text-slate-500 md:block max-w-xl truncate">
            {viewInfo.subtitle}
          </p>
        </div>
      </div>

      {/* Right Controls */}
      <div className="flex items-center gap-2.5 sm:gap-4">
        {/* Search Bar */}
        <div className="relative hidden xl:block w-64">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
          <input
            ref={searchInputRef}
            type="text"
            placeholder="Search leads, companies..."
            value={searchQuery}
            onChange={(e) => onSearchChange?.(e.target.value)}
            className="w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-12 py-1.5 text-xs text-slate-900 placeholder:text-slate-400 focus:bg-white focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all shadow-2xs"
          />
          <div className="absolute right-2.5 top-1/2 -translate-y-1/2 flex items-center gap-0.5 rounded border border-slate-200 bg-white px-1 py-0.5 text-[10px] text-slate-400 font-mono pointer-events-none">
            <Command className="h-2.5 w-2.5" /> K
          </div>
        </div>

        {/* Live Status indicator */}
        {isBackendConnected ? (
          <div className="hidden sm:flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800 shadow-2xs">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
            </span>
            <span>API Live (SQLite)</span>
          </div>
        ) : (
          <button
            onClick={onRetryConnection}
            className="hidden sm:flex items-center gap-2 rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-800 hover:bg-amber-100 transition-colors cursor-pointer shadow-2xs"
            title="Click to reconnect to backend"
          >
            <span className="h-2 w-2 rounded-full bg-amber-500"></span>
            <span>Offline (Cached) • Retry</span>
          </button>
        )}

        {/* Trigger Autonomous Scan Button */}
        <button
          onClick={handleSimulateScan}
          disabled={isScanning}
          className="relative inline-flex items-center gap-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 px-3 sm:px-3.5 py-1.5 sm:py-2 text-xs font-semibold text-white shadow-xs transition-all active:scale-95 disabled:opacity-60 cursor-pointer"
        >
          {isScanning ? (
            <RefreshCw className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Sparkles className="h-3.5 w-3.5 text-amber-300" />
          )}
          <span className="hidden sm:inline">
            {isScanning ? 'Scanning...' : 'Trigger AI Discovery'}
          </span>
          <span className="sm:hidden">{isScanning ? 'Scanning' : 'Scan'}</span>
        </button>

        {/* Notifications Popover */}
        <div className="relative">
          <button
            onClick={() => setShowNotifications(!showNotifications)}
            className="relative rounded-xl border border-slate-200 bg-white p-2 text-slate-500 hover:bg-slate-50 hover:text-slate-900 transition-colors cursor-pointer shadow-2xs"
            aria-label="View notifications"
          >
            <Bell className="h-4 w-4" />
            <span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-orange-500 text-[9px] font-bold text-white shadow-xs">
              {Math.min(activities.length, 9)}
            </span>
          </button>

          {showNotifications && (
            <div className="absolute right-0 mt-2 w-80 rounded-2xl border border-slate-200 bg-white p-4 shadow-xl z-50 animate-in fade-in zoom-in-95">
              <div className="flex items-center justify-between pb-3 border-b border-slate-100">
                <span className="text-xs font-bold text-slate-900">Autonomous Alerts</span>
                <span
                  onClick={() => setShowNotifications(false)}
                  className="text-[10px] text-indigo-600 font-medium cursor-pointer hover:underline"
                >
                  Close
                </span>
              </div>
              <div className="mt-3 space-y-2.5 max-h-72 overflow-y-auto pr-1">
                {activities.length === 0 ? (
                  <p className="text-xs text-slate-500 py-3 text-center">No alerts yet</p>
                ) : (
                  activities.slice(0, 4).map((act) => (
                    <div key={act.id} className="rounded-lg bg-slate-50 border border-slate-100 p-2.5 text-xs">
                      <div className="flex items-center gap-1.5 font-semibold text-emerald-700">
                        <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />
                        {act.title}
                      </div>
                      <p className="mt-0.5 text-slate-600 line-clamp-2">{act.description}</p>
                      <span className="mt-1 block text-[10px] text-slate-400">{act.timestamp}</span>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Floating Scan Notification Toast */}
      {scanMessage && (
        <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2.5 rounded-xl border border-slate-800 bg-slate-900 px-4 py-3 text-xs font-semibold text-white shadow-xl backdrop-blur-md animate-in slide-in-from-bottom-5">
          <Sparkles className="h-4 w-4 text-amber-400 animate-spin" />
          <span>{scanMessage}</span>
        </div>
      )}
    </header>
  );
};
